export const ADDRESSES = [
  {
    Address1: "421 W Lawson R Try 68",
    Address2: "",
    City: "",
    State: "TX",
    Zip5: "75253",
    Zip4: "",
  },
  {
    Address1: "2100 W. Cypress Creek Rd. Suite 130",
    Address2: "",
    City: "",
    State: "FL",
    Zip5: "33309",
    Zip4: "",
  },
  {
    Address1: "00620 MULBERRY ST",
    Address2: "",
    City: "TEAGUE",
    State: "TX",
    Zip5: "",
    Zip4: "",
  },
  {
    Address1: "5454 WESTGULF BANK #112",
    Address2: "",
    City: "HOUSTON",
    State: "TX",
    Zip5: "",
    Zip4: "",
  },
  {
    Address1: "1170 BROADWAY",
    Address2: "STE 908",
    City: "",
    State: "NY",
    Zip5: "10001",
    Zip4: "",
  },
  {
    Address1: "92 W Main St",
    Address2: "",
    City: "Chester",
    State: "CT",
    Zip5: "06412",
    Zip4: "",
  },
  {
    Address1: "3051 Baychester Avenue",
    Address2: "",
    City: "Bronx",
    State: "NY",
    Zip5: "10402",
    Zip4: "",
  },
  {
    Address1: "1558 Union Port Rd",
    Address2: "",
    City: "Bronx",
    State: "NY",
    Zip5: "10462",
    Zip4: "",
  },
  {
    Address1: "217 New Meadow Rd",
    Address2: "",
    City: "",
    State: "RI",
    Zip5: "02806",
    Zip4: "",
  },
  {
    Address1: "14900 Lasater Rd Trlr 214",
    Address2: "",
    City: "",
    State: "TX",
    Zip5: "75253",
    Zip4: "",
  },
];
